//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.468
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftAuthenticator.CommandLine.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiftAuthenticator.CommandLine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account {0} of {1}: ähnelt.
        /// </summary>
        internal static string app_account_n_of_m {
            get {
                return ResourceManager.GetString("app_account_n_of_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} [global-options] &lt;command-name&gt; [command-options] ähnelt.
        /// </summary>
        internal static string app_command_line {
            get {
                return ResourceManager.GetString("app_command_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commands: ähnelt.
        /// </summary>
        internal static string app_commands {
            get {
                return ResourceManager.GetString("app_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: {0} ähnelt.
        /// </summary>
        internal static string app_info_description {
            get {
                return ResourceManager.GetString("app_info_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device ID: {0} ähnelt.
        /// </summary>
        internal static string app_info_device_id {
            get {
                return ResourceManager.GetString("app_info_device_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encrypted Secret Key: {0} ähnelt.
        /// </summary>
        internal static string app_info_encrypted_secret_key {
            get {
                return ResourceManager.GetString("app_info_encrypted_secret_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serial Key: {0} ähnelt.
        /// </summary>
        internal static string app_info_serial_key {
            get {
                return ResourceManager.GetString("app_info_serial_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Offset: {0} ähnelt.
        /// </summary>
        internal static string app_info_time_offset {
            get {
                return ResourceManager.GetString("app_info_time_offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No valid command specified: {0} ähnelt.
        /// </summary>
        internal static string app_invalid_command {
            get {
                return ResourceManager.GetString("app_invalid_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No account with the id {0} found. ähnelt.
        /// </summary>
        internal static string app_no_account_found {
            get {
                return ResourceManager.GetString("app_no_account_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No command name specified. ähnelt.
        /// </summary>
        internal static string app_no_command {
            get {
                return ResourceManager.GetString("app_no_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration is empty. ähnelt.
        /// </summary>
        internal static string app_no_config {
            get {
                return ResourceManager.GetString("app_no_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global options: ähnelt.
        /// </summary>
        internal static string app_opt_global {
            get {
                return ResourceManager.GetString("app_opt_global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown arguments found: {0} ähnelt.
        /// </summary>
        internal static string app_unknown_args {
            get {
                return ResourceManager.GetString("app_unknown_args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete a existing account ähnelt.
        /// </summary>
        internal static string opt_delete_account_description {
            get {
                return ResourceManager.GetString("opt_delete_account_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specifiy the account to use ähnelt.
        /// </summary>
        internal static string opt_global_account {
            get {
                return ResourceManager.GetString("opt_global_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specify the account manager to use ähnelt.
        /// </summary>
        internal static string opt_global_account_manager {
            get {
                return ResourceManager.GetString("opt_global_account_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show help ähnelt.
        /// </summary>
        internal static string opt_global_help {
            get {
                return ResourceManager.GetString("opt_global_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set verbose level ähnelt.
        /// </summary>
        internal static string opt_global_verbose {
            get {
                return ResourceManager.GetString("opt_global_verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options for command {0} ({1}): ähnelt.
        /// </summary>
        internal static string opt_help_cmd_options {
            get {
                return ResourceManager.GetString("opt_help_cmd_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show help for a command ähnelt.
        /// </summary>
        internal static string opt_help_description {
            get {
                return ResourceManager.GetString("opt_help_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show current configuration ähnelt.
        /// </summary>
        internal static string opt_info_description {
            get {
                return ResourceManager.GetString("opt_info_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A configuration already exists, but the -f (force) option wasn&apos;t specified. ähnelt.
        /// </summary>
        internal static string opt_init_config_found {
            get {
                return ResourceManager.GetString("opt_init_config_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialization of a new authenticator ähnelt.
        /// </summary>
        internal static string opt_init_description {
            get {
                return ResourceManager.GetString("opt_init_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manually specify a device id ähnelt.
        /// </summary>
        internal static string opt_init_opt_device_id {
            get {
                return ResourceManager.GetString("opt_init_opt_device_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force overwrite of current configuration ähnelt.
        /// </summary>
        internal static string opt_init_opt_force {
            get {
                return ResourceManager.GetString("opt_init_opt_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show current login token ähnelt.
        /// </summary>
        internal static string opt_login_token_description {
            get {
                return ResourceManager.GetString("opt_login_token_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login token: {0} ähnelt.
        /// </summary>
        internal static string opt_login_token_login_token {
            get {
                return ResourceManager.GetString("opt_login_token_login_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining time (ms): {0} ähnelt.
        /// </summary>
        internal static string opt_login_token_remaining_time {
            get {
                return ResourceManager.GetString("opt_login_token_remaining_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account {0} ähnelt.
        /// </summary>
        internal static string opt_new_account_default_name {
            get {
                return ResourceManager.GetString("opt_new_account_default_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new account ähnelt.
        /// </summary>
        internal static string opt_new_account_description {
            get {
                return ResourceManager.GetString("opt_new_account_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of the new account ähnelt.
        /// </summary>
        internal static string opt_new_account_name {
            get {
                return ResourceManager.GetString("opt_new_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recover the authenticators configuration ähnelt.
        /// </summary>
        internal static string opt_recover_description {
            get {
                return ResourceManager.GetString("opt_recover_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No answer for security question {0} ({1}) given ähnelt.
        /// </summary>
        internal static string opt_recover_error_no_answer {
            get {
                return ResourceManager.GetString("opt_recover_error_no_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No email address (user name) for login specified ähnelt.
        /// </summary>
        internal static string opt_recover_error_no_email {
            get {
                return ResourceManager.GetString("opt_recover_error_no_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No password for login specified ähnelt.
        /// </summary>
        internal static string opt_recover_error_no_password {
            get {
                return ResourceManager.GetString("opt_recover_error_no_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manually specify a device id ähnelt.
        /// </summary>
        internal static string opt_recover_opt_device_id {
            get {
                return ResourceManager.GetString("opt_recover_opt_device_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email address used for login ähnelt.
        /// </summary>
        internal static string opt_recover_opt_email {
            get {
                return ResourceManager.GetString("opt_recover_opt_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password used for login ähnelt.
        /// </summary>
        internal static string opt_recover_opt_password {
            get {
                return ResourceManager.GetString("opt_recover_opt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show the users secret question(s) ähnelt.
        /// </summary>
        internal static string opt_secret_questions_description {
            get {
                return ResourceManager.GetString("opt_secret_questions_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security question {0}: {1} ähnelt.
        /// </summary>
        internal static string opt_secret_questions_display {
            get {
                return ResourceManager.GetString("opt_secret_questions_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No email address (user name) for login specified ähnelt.
        /// </summary>
        internal static string opt_secret_questions_error_no_email {
            get {
                return ResourceManager.GetString("opt_secret_questions_error_no_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No password for login specified ähnelt.
        /// </summary>
        internal static string opt_secret_questions_error_no_password {
            get {
                return ResourceManager.GetString("opt_secret_questions_error_no_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email address used for login ähnelt.
        /// </summary>
        internal static string opt_secret_questions_opt_email {
            get {
                return ResourceManager.GetString("opt_secret_questions_opt_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password used for login ähnelt.
        /// </summary>
        internal static string opt_secret_questions_opt_password {
            get {
                return ResourceManager.GetString("opt_secret_questions_opt_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time synchronization with TRION&apos;s login server ähnelt.
        /// </summary>
        internal static string opt_time_sync_description {
            get {
                return ResourceManager.GetString("opt_time_sync_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New time offset: {0} ähnelt.
        /// </summary>
        internal static string opt_time_sync_display {
            get {
                return ResourceManager.GetString("opt_time_sync_display", resourceCulture);
            }
        }
    }
}
