//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.468
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiftAuthenticator.WinForms.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiftAuthenticator.WinForms.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is the RIFT™ Authenticator for Windows written by the RIFT™ Authenticator for Windows Project. ähnelt.
        /// </summary>
        internal static string MessageBox_Message_About {
            get {
                return ResourceManager.GetString("MessageBox_Message_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authenticator already initialized!
        ///Reinitialization will make you loose your current configuration!
        ///Continue? ähnelt.
        /// </summary>
        internal static string MessageBox_Message_AlreadyInitialized {
            get {
                return ResourceManager.GetString("MessageBox_Message_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This application is distributed under the terms of GNU General Public License Version 3.
        ///The application is under copyright of the RIFT™ Authenticator for Windows project except for some parts which are under the copyright of the following companies/projects:
        ///Novell
        ///The Apache Software Foundation ähnelt.
        /// </summary>
        internal static string MessageBox_Message_License {
            get {
                return ResourceManager.GetString("MessageBox_Message_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No user name or password given. ähnelt.
        /// </summary>
        internal static string MessageBox_Message_LoginInfoIncomplete {
            get {
                return ResourceManager.GetString("MessageBox_Message_LoginInfoIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device ID given. ähnelt.
        /// </summary>
        internal static string MessageBox_Message_NoDeviceId {
            get {
                return ResourceManager.GetString("MessageBox_Message_NoDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device id has been copied into your clipboard.
        ///Save it!
        ///The device id is required to use the restore functionality!
        ///The device id is {0}. ähnelt.
        /// </summary>
        internal static string MessageBox_Message_RememberDeviceId {
            get {
                return ResourceManager.GetString("MessageBox_Message_RememberDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RIFT™ Authenticator for Windows ähnelt.
        /// </summary>
        internal static string MessageBox_Title_About {
            get {
                return ResourceManager.GetString("MessageBox_Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MessageBox_Title_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License information ähnelt.
        /// </summary>
        internal static string MessageBox_Title_License {
            get {
                return ResourceManager.GetString("MessageBox_Title_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember you device id ähnelt.
        /// </summary>
        internal static string MessageBox_Title_RememberDeviceId {
            get {
                return ResourceManager.GetString("MessageBox_Title_RememberDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input error ähnelt.
        /// </summary>
        internal static string MessageBox_Title_UserInputError {
            get {
                return ResourceManager.GetString("MessageBox_Title_UserInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die R U sure? ähnelt.
        /// </summary>
        internal static string MessageBox_Title_Warning {
            get {
                return ResourceManager.GetString("MessageBox_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No configuration found. Initialization required. ähnelt.
        /// </summary>
        internal static string Status_NoConfig {
            get {
                return ResourceManager.GetString("Status_NoConfig", resourceCulture);
            }
        }
    }
}
